# Generated by Django 3.2.14 on 2022-07-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=60)),
            ],
        ),
    ]
